execute store result score rng_tip master run loot spawn 0 100 0 loot mafia:custom/random_tip

execute if score tip master matches 0 run scoreboard players set rng_tip master -1

execute if score rng_tip master matches 00 run tellraw @a ["",{"translate":"mafia.tip.00","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 01 run tellraw @a ["",{"translate":"mafia.tip.01","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 02 run tellraw @a ["",{"translate":"mafia.tip.02","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 03 run tellraw @a ["",{"translate":"mafia.tip.03","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 04 run tellraw @a ["",{"translate":"mafia.tip.04","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 05 run tellraw @a ["",{"translate":"mafia.tip.05","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 06 run tellraw @a ["",{"translate":"mafia.tip.06","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 07 run tellraw @a ["",{"translate":"mafia.tip.07","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 08 run tellraw @a ["",{"translate":"mafia.tip.08","italic":false,"color":"white","bold":false,"with":[{"keybind":"key.advancements"}]}]
execute if score rng_tip master matches 09 run tellraw @a ["",{"translate":"mafia.tip.09","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 10 run tellraw @a ["",{"translate":"mafia.tip.10","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 11 run tellraw @a ["",{"translate":"mafia.tip.11","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 12 run tellraw @a ["",{"translate":"mafia.tip.12","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 13 run tellraw @a ["",{"translate":"mafia.tip.13","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 14 run tellraw @a ["",{"translate":"mafia.tip.14","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 15 run tellraw @a ["",{"translate":"mafia.tip.15","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 16 run tellraw @a ["",{"translate":"mafia.tip.16","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 17 run tellraw @a ["",{"translate":"mafia.tip.17","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 18 run tellraw @a ["",{"translate":"mafia.tip.18","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 19 run tellraw @a ["",{"translate":"mafia.tip.19","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 20 run tellraw @a ["",{"translate":"mafia.tip.20","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 21 run tellraw @a ["",{"translate":"mafia.tip.21","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 22 run tellraw @a ["",{"translate":"mafia.tip.22","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 23 run tellraw @a ["",{"translate":"mafia.tip.23","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 24 run tellraw @a ["",{"translate":"mafia.tip.24","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 25 run tellraw @a ["",{"translate":"mafia.tip.25","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 26 run tellraw @a ["",{"translate":"mafia.tip.26","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 27 run tellraw @a ["",{"translate":"mafia.tip.27","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 28 run tellraw @a ["",{"translate":"mafia.tip.28","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 29 run tellraw @a ["",{"translate":"mafia.tip.29","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 30 run tellraw @a ["",{"translate":"mafia.tip.30","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 31 run tellraw @a ["",{"translate":"mafia.tip.31","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 32 run tellraw @a ["",{"translate":"mafia.tip.32","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 33 run tellraw @a ["",{"translate":"mafia.tip.33","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 34 run tellraw @a ["",{"translate":"mafia.tip.34","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 35 run tellraw @a ["",{"translate":"mafia.tip.35","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 36 run tellraw @a ["",{"translate":"mafia.tip.36","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 37 run tellraw @a ["",{"translate":"mafia.tip.37","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 38 run tellraw @a ["",{"translate":"mafia.tip.38","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 39 run tellraw @a ["",{"translate":"mafia.tip.39","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 40 run tellraw @a ["",{"translate":"mafia.tip.40","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 41 run tellraw @a ["",{"translate":"mafia.tip.41","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 42 run tellraw @a ["",{"translate":"mafia.tip.42","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 43 run tellraw @a ["",{"translate":"mafia.tip.43","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 44 run tellraw @a ["",{"translate":"mafia.tip.44","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 45 run tellraw @a ["",{"translate":"mafia.tip.45","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 46 run tellraw @a ["",{"translate":"mafia.tip.46","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 47 run tellraw @a ["",{"translate":"mafia.tip.47","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 48 run tellraw @a ["",{"translate":"mafia.tip.48","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 49 run tellraw @a ["",{"translate":"mafia.tip.49","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 50 run tellraw @a ["",{"translate":"mafia.tip.50","italic":false,"color":"white","bold":false}]
execute if score rng_tip master matches 51 run tellraw @a ["",{"translate":"mafia.tip.51","italic":false,"color":"white","bold":false}]

schedule function mafia:ingame/tip 30s